### ISSUE TITLE
Attempting to write on read only database

### ISSUE THREAD

**Issue by AzadKshitij** [unfoldadmin/formula#13]
```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, django_celery_beat, formula, guardian, sessions
Running migrations:
Traceback (most recent call last):
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 325, in execute
    return super().execute(query)
           ^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\migrations\recorder.py", line 78, in ensure_schema
    editor.create_model(self.Migration)
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\base\schema.py", line 488, in create_model
    self.execute(sql, params or None)
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\base\schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\utils.py", line 103, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 325, in execute
    return super().execute(query)
           ^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: attempt to write a readonly database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Startup\formula\src\manage.py", line 22, in <module>
    main()
  File "D:\Startup\formula\src\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\Startup\formula\venv\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "D:\Startup\formula\venv\Lib\site-packages\django\core\management\__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Startup\formula\venv\Lib\site-packages\django\core\management\base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Startup\formula\venv\Lib\site-packages\django\core\management\base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Startup\formula\venv\Lib\site-packages\django\core\management\base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Startup\formula\venv\Lib\site-packages\django\core\management\commands\migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\migrations\executor.py", line 107, in migrate
    self.recorder.ensure_schema()
  File "D:\Startup\formula\venv\Lib\site-packages\django\db\migrations\recorder.py", line 80, in ensure_schema
    raise MigrationSchemaMissing(
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table (attempt to write a readonly database)
```

**Comment by AzadKshitij** [comment]
run this command inside formula folder.
`chmod 666 ./`
